name: Build and deploy my Blog
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v3

      - name: Install latest Node 
        uses: actions/setup-node@v3
        
      - name: Running npm command
        run: npm run-script build

      - name: Deploy docs folder to gh-pages
        run: |
          git checkout --orphan gh-pages
          git --work-tree docs add --all
          git --work-tree docs commit -m "push blogs built to gh-pages"
          git push origin HEAD:gh-pages --force
          git checkout -f main


    
